name: Build and publish Docker image

on:
  push:
    branches: [ main ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/invoice:latest
            ghcr.io/${{ github.repository_owner }}/invoice:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  e2e-smoke:
    name: E2E Smoke (build and run tests in container)
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image (local)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: invoice:e2e-smoke

      - name: Run container and execute e2e script
        run: |
          docker run --rm -d --name invoice-e2e -p 3005:3000 invoice:e2e-smoke
          # wait for container to be ready
          timeout=60
          until curl -s http://localhost:3005 || [ $timeout -le 0 ]; do
            sleep 1; timeout=$((timeout-1))
          done
          docker exec invoice-e2e bash -lc "cd /app && bash test_e2e.sh"
